language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  code_climate:
    repo_token: ccb3c8b6bf3740ae6648b4417313c84f955e5c98388656fff60e18641f6b98d8
